kind: pipeline
type: docker
name: docker-compiler

workspace:
  path: /out

steps:
- name: check
  image: composer:latest
  volumes:
  - name: tgbuild
    path: /persistent_data
  commands:
  - mkdir -p /app && cd /app
  - apk add curl
  - |
    if -f /persistent_data/old_md5; then
      cp /persistent_data/old_md5 .;
    else
      touch /persistent_data/old_md5;
    fi;
  - curl -Ls https://core.telegram.org/bots/api | grep -v "page generated" | md5sum > new_md5;
  - |
    if [ -n "$(diff new_md5 old_md5)" ]; then 
      exit 1;
    else
      rm /persistent_data/old_md5
      cp new_md5 /persistent_data/old_md5
      composer require sysbot/tgscraper sysbot/tgscraper-cache --prefer-stable
      /app/vendor/bin/tgscraper app:export-schema --readable botapi.json
      cp botapi.json /out
    fi;

- name: rebuild api.php
  image: php:8.2
  commands:
  - apt --assume-yes update && apt install -yf git
  - mv api.php old_api.php
  - cp /out/botapi.json .
  - php gen.php
  - |
    if [ -n "$(diff api.php old_api.php)" ]; then 
      exit 1
    else
      rm old_api.php;
    fi;

- name: git-push
  image: appleboy/drone-git-push
  settings:
    ssh_key:
      from_secret: GITHUB_SSH_PRIV_KEY
    commit: "CI: Update api.php"
    branch: master
    remote: git@github.com:davtur19/TuriBotGen.git
    force: false
    commit: true

volumes:
- name: tgbuild
  host:
    path: /srv/drone/data/tgbuild

trigger:
  event:
  - cron
  cron:
  - tgbuild
  branch:
  - master
